In [66]:
# Python 3.10.11
%pip install -r requirements.txt > /dev/null

from args import *

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [67]:
import os
import pandas as pd
from pathlib import Path

In [68]:
gene_df = pd.read_csv(valid_gene_file_path, index_col=0)

In [69]:
module_color2sample_dict = {}
for root, _, files in os.walk(data_output_dir_path / "connect_top"):
    for file in files:
        if file.endswith("_connect_top.csv"):
            # print(os.path.join(root, file))
            df = pd.read_csv(os.path.join(root, file))
            file = file.replace("_connect_top.csv", "")
            if file not in module_color2sample_dict:
                module_color2sample_dict[file] = df['sample'].to_list()
            else:
                module_color2sample_dict[file] = module_color2sample_dict[file].append(df['sample'].to_list())

In [70]:
color2count = [(color, len(sample_key_list)) for color, sample_key_list in module_color2sample_dict.items()]
color2count = sorted(color2count, key=lambda x: x[1], reverse=True)

In [71]:
sample_key_list = []
for color, _ in color2count:
    key_list = module_color2sample_dict[color]
    sample_key_list.extend(key_list)

In [72]:
wgcna_df = gene_df.loc[sample_key_list]
wgcna_df.to_csv(data_output_dir_path / "wgcna.csv")
print(wgcna_df.shape)

(2340, 308)

In [73]:
wgcna_df.head()

,TCGA-EA-A3HT-01,TCGA-FU-A3HZ-01,TCGA-FU-A3TQ-01,TCGA-DS-A0VK-01,TCGA-UC-A7PG-01,TCGA-C5-A7UE-01,TCGA-C5-A1MJ-01,TCGA-UC-A7PI-01,TCGA-C5-A1MF-01,TCGA-EA-A5ZF-01,...,TCGA-JW-A5VI-01,TCGA-VS-A9UD-01,TCGA-C5-A1BQ-01,TCGA-MU-A8JM-01,TCGA-DS-A0VM-01,TCGA-MY-A5BF-01,TCGA-EA-A556-01,TCGA-IR-A3LA-01,TCGA-VS-AA62-01,TCGA-ZJ-AAXB-01
sample,,,,,,,,,,,,,,,,,,,,,
REST,8.0548,7.5314,7.7721,6.8449,8.1648,3.8391,8.0490,7.7224,1.3127,7.2768,...,7.6476,3.2886,7.3606,7.3372,5.3219,7.0019,7.7200,8.0599,8.7806,5.6470
CCNT1,7.0190,5.7922,7.1959,5.4446,7.8248,3.9468,7.7452,6.6382,1.6898,5.6989,...,6.8323,2.4292,6.4738,6.4199,4.4772,5.9717,5.6358,6.0018,7.7133,3.4624
NCOA2,8.6813,6.7035,9.5358,7.8279,9.3336,4.0946,9.4207,9.3338,3.0739,7.6837,...,7.9219,2.8360,8.1919,7.5495,6.6896,8.3046,8.0439,8.8754,8.8973,3.4624
SHPRH,8.2532,7.0519,8.1232,7.5072,8.2057,4.9213,8.8297,8.2231,0.8007,6.9430,...,7.8640,3.9640,7.3685,6.9337,6.2698,7.8458,6.2938,8.9222,8.1718,3.2539
ASXL2,9.2590,8.2153,9.4407,8.1023,9.3820,5.7614,9.6833,8.9079,3.7671,8.0169,...,8.6060,5.6724,8.3648,8.6007,6.9770,7.8779,7.9653,9.2762,9.6598,6.0693

In [114]:
copy_number_df = pd.read_csv(copy_number_file_path, sep="\t", index_col=0)
copy_number_df = pd.read_csv(copy_number_thresholded_file_path, sep="\t", index_col=0)

In [115]:
copy_number_df.head()

,TCGA-2W-A8YY-01,TCGA-4J-AA1J-01,TCGA-BI-A0VR-01,TCGA-BI-A0VS-01,TCGA-BI-A20A-01,TCGA-C5-A0TN-01,TCGA-C5-A1BE-01,TCGA-C5-A1BF-01,TCGA-C5-A1BI-01,TCGA-C5-A1BJ-01,...,TCGA-ZJ-AAXD-01,TCGA-ZJ-AAXF-01,TCGA-ZJ-AAXI-01,TCGA-ZJ-AAXJ-01,TCGA-ZJ-AAXN-01,TCGA-ZJ-AAXT-01,TCGA-ZJ-AAXU-01,TCGA-ZJ-AB0H-01,TCGA-ZJ-AB0I-01,TCGA-ZX-AA5X-01
Gene Symbol,,,,,,,,,,,,,,,,,,,,,
ACAP3,0,0,1,1,0,-1,0,0,1,0,...,1,1,1,0,-1,0,0,0,1,1
ACTRT2,0,0,1,1,0,-1,0,0,1,0,...,1,1,1,0,-1,0,0,0,1,1
AGRN,0,0,1,1,0,-1,0,0,1,0,...,1,1,1,0,-1,0,0,0,1,1
ANKRD65,0,0,1,1,0,-1,0,0,1,0,...,1,1,1,0,-1,0,0,0,1,1
ATAD3A,0,0,1,1,0,-1,0,0,1,0,...,1,1,1,0,-1,0,0,0,1,1

In [116]:
copy_number_key_list = copy_number_df.index.tolist()
not_in_copy_number_key_list = []
for key in sample_key_list:
    if key not in copy_number_key_list:
        not_in_copy_number_key_list.append(key)
print(f"基因样本数量: {len(sample_key_list)}")
print("拷贝数缺失数量: ", len(not_in_copy_number_key_list), not_in_copy_number_key_list[:5])

for key in not_in_copy_number_key_list:
    new_row = {col:0 for col in copy_number_df.columns}
    copy_number_df.loc[key] = new_row
copy_number_df = copy_number_df.loc[sample_key_list, :]
print(f"拷贝数样本数量: {len(copy_number_df)}")

copy_number_df.to_csv(data_output_dir_path / "copy-number.csv")

基因样本数量: 2340
拷贝数缺失数量:  192 ['ZNF192', 'LOC284441', 'C1orf58', 'CSNK2A1P', 'MLL2']
拷贝数样本数量: 2340